sudo: required
services:
    - docker

before_install:
    - docker build -t kolibomber/first-ci-cd-project -f Dockerfile.dev .

script:
    - docker run -p 80:80 -v ${PWD}/index.html:/usr/share/ngins/html/index.html kolibomber/First-CI-CD-project